apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-n7pf
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0071-tenant/tkrw-pr712-0075-0071-app/devfile-sample-n7pf@sha256:aa27f64283d5093e7dd10a94e10cac8abae0f371a8f8cbd6e2261e92a8cd6539
        name: my-nodejs
        resources: {}
status: {}
